### ISSUE TITLE
Is there away to detect the current operating mode?

### ISSUE THREAD

**Issue by ronzelver** [robertklep/homebridge-nefit-easy#28]
When I restart HomeBridge the Nefit Easy thermostat always comes back in an 'Off' state while actually the thermostat is in 'Automatic' mode. Is this something the API supports? Or, in case it doesn't, can you force at startup with a configuration parameter?

**Comment by robertklep** [comment]
> Is this something the API supports?

Homekit supports three values for the current state: heating, cooling or off. There's no "automatic" equivalent :(

**Comment by ronzelver** [comment]
Robert,

In the Home app I can manually select 4 status for heating/cooling control: Off, Cooling, Heating, Automatic. 
For the Daikin plugin this works accordingly, so I don't think it's a Homekit API restriction?!

Best regards,
Ron

**Comment by robertklep** [comment]
It's a bit confusing.

You can select Automatic for the Daikin plugin because that's how you can control the _target_ state of the device.

However, when it shows the _current_ state, it will not show Automatic either, like the Nefit plugin, because the current state in Homekit doesn't support that value.

The Nefit plugin doesn't support changing the (target) state at all, it can only show the current state the thermostat is in.

Hope that makes sense 😬

**Comment by ronzelver** [comment]
OK, thanks for the explanation!
